"""
Repository: invite tokens for pre-validated user signups.

Invite tokens are generated by admins and allow new users to sign up
with automatic approval (skipping the pending → approve workflow).
"""
import secrets
import hashlib
from datetime import datetime, timezone, timedelta
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.db.models import InviteTokenORM


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


async def create_invite_token(
    session: AsyncSession,
    created_by: str,
    role: str = "user",
    email: Optional[str] = None,
    label: Optional[str] = None,
    max_uses: int = 1,
    expiry_hours: int = 72,
) -> tuple[str, InviteTokenORM]:
    """Create an invite token. Returns (raw_token, orm_object)."""
    raw_token = secrets.token_urlsafe(32)
    expires_at = (datetime.now(timezone.utc) + timedelta(hours=expiry_hours)).isoformat()

    invite = InviteTokenORM(
        token_hash=_hash_token(raw_token),
        created_by=created_by,
        role=role,
        email=email.strip().lower() if email else None,
        label=label,
        max_uses=max_uses,
        expires_at=expires_at,
    )
    session.add(invite)
    await session.flush()
    return raw_token, invite


async def verify_invite_token(
    session: AsyncSession,
    token: str,
    email: Optional[str] = None,
) -> Optional[InviteTokenORM]:
    """
    Validate an invite token. Returns the ORM object if valid, None otherwise.
    Checks: exists, not revoked, not expired, not exhausted, email match (if restricted).
    Does NOT increment use_count — call consume_invite_token after successful signup.
    """
    token_hash = _hash_token(token)
    result = await session.execute(
        select(InviteTokenORM).where(
            InviteTokenORM.token_hash == token_hash,
            InviteTokenORM.revoked.is_(False),
        )
    )
    invite = result.scalar_one_or_none()
    if invite is None:
        return None

    # Check expiry
    expires = datetime.fromisoformat(invite.expires_at)
    if datetime.now(timezone.utc) > expires:
        return None

    # Check usage
    if invite.use_count >= invite.max_uses:
        return None

    # Check email restriction
    if invite.email and email and invite.email != email.strip().lower():
        return None

    return invite


async def consume_invite_token(session: AsyncSession, invite_id: str) -> None:
    """Increment use_count after a successful signup."""
    result = await session.execute(
        select(InviteTokenORM).where(InviteTokenORM.id == invite_id)
    )
    invite = result.scalar_one_or_none()
    if invite:
        invite.use_count += 1
        await session.flush()


async def revoke_invite_token(session: AsyncSession, invite_id: str) -> Optional[InviteTokenORM]:
    """Revoke an invite token."""
    result = await session.execute(
        select(InviteTokenORM).where(InviteTokenORM.id == invite_id)
    )
    invite = result.scalar_one_or_none()
    if invite:
        invite.revoked = True
        await session.flush()
    return invite


async def list_invite_tokens(session: AsyncSession, include_revoked: bool = False) -> list[InviteTokenORM]:
    """List invite tokens, optionally including revoked ones."""
    stmt = select(InviteTokenORM)
    if not include_revoked:
        stmt = stmt.where(InviteTokenORM.revoked.is_(False))
    stmt = stmt.order_by(InviteTokenORM.created_at.desc())
    result = await session.execute(stmt)
    return list(result.scalars().all())


async def get_invite_token_by_id(session: AsyncSession, invite_id: str) -> Optional[InviteTokenORM]:
    result = await session.execute(
        select(InviteTokenORM).where(InviteTokenORM.id == invite_id)
    )
    return result.scalar_one_or_none()
