"""
System default entity and relationship type definitions.

These constants are the source-of-truth for the built-in ontology that ships
with Synodic.  They are loaded ONCE at startup by seed_system_defaults() and
written into the DB.  From that point on, the DB is the authoritative copy.

Anything currently hardcoded in context_engine.py, falkordb_provider.py,
or frontend/src/store/* is expected to migrate here, then be deleted.
"""
from typing import Any, Dict

# ---------------------------------------------------------------------------
# Entity type visual/hierarchy defaults
# ---------------------------------------------------------------------------
# Schema mirrors EntityTypeDefEntry in models.py.
# Keys are the entity type IDs that flow through GraphNode.entity_type.

SYSTEM_ENTITY_TYPES: Dict[str, Dict[str, Any]] = {
    "domain": {
        "name": "Domain",
        "plural_name": "Domains",
        "description": "Business domain grouping related entities under a governance boundary.",
        "granularity": "domain",
        "visual": {
            "icon": "FolderTree",
            "color": "#8b5cf6",
            "color_secondary": "#7c3aed",
            "shape": "rounded",
            "size": "lg",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 0,
            "can_contain": ["system", "dataPlatform", "app", "domain"],
            "can_be_contained_by": [],
            "default_expanded": True,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
            {"id": "description", "name": "Description", "type": "markdown", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": False, "display_order": 2},
            {"id": "owner", "name": "Owner", "type": "string", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": False, "display_order": 3},
        ],
    },
    "system": {
        "name": "System",
        "plural_name": "Systems",
        "description": "A system or platform that hosts data assets.",
        "granularity": "system",
        "visual": {
            "icon": "Database",
            "color": "#06b6d4",
            "color_secondary": "#0891b2",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 1,
            "can_contain": ["schema", "container", "dataset", "dataFlow", "pipeline"],
            "can_be_contained_by": ["domain"],
            "default_expanded": True,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
            {"id": "description", "name": "Description", "type": "markdown", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": False, "display_order": 2},
        ],
    },
    "dataPlatform": {
        "name": "Data Platform",
        "plural_name": "Data Platforms",
        "description": "A data platform such as Snowflake, BigQuery, or dbt.",
        "granularity": "system",
        "visual": {
            "icon": "Server",
            "color": "#06b6d4",
            "color_secondary": "#0891b2",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 1,
            "can_contain": ["schema", "container", "dataset"],
            "can_be_contained_by": ["domain"],
            "default_expanded": True,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "app": {
        "name": "Application",
        "plural_name": "Applications",
        "description": "A software application or service.",
        "granularity": "system",
        "visual": {
            "icon": "AppWindow",
            "color": "#06b6d4",
            "color_secondary": "#0891b2",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 1,
            "can_contain": [],
            "can_be_contained_by": ["domain"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": False,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "container": {
        "name": "Container",
        "plural_name": "Containers",
        "description": "A logical container grouping datasets (e.g. folder, bucket, schema).",
        "granularity": "schema",
        "visual": {
            "icon": "Box",
            "color": "#10b981",
            "color_secondary": "#059669",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 2,
            "can_contain": ["container", "dataset"],
            "can_be_contained_by": ["system", "dataPlatform"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "schema": {
        "name": "Schema",
        "plural_name": "Schemas",
        "description": "A database schema or namespace.",
        "granularity": "schema",
        "visual": {
            "icon": "Layers",
            "color": "#10b981",
            "color_secondary": "#059669",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 2,
            "can_contain": ["dataset", "dataJob"],
            "can_be_contained_by": ["system", "dataPlatform"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "dataFlow": {
        "name": "Data Flow",
        "plural_name": "Data Flows",
        "description": "A logical orchestration pipeline or workflow grouping jobs.",
        "granularity": "schema",
        "visual": {
            "icon": "GitBranch",
            "color": "#ec4899",
            "color_secondary": "#db2777",
            "shape": "diamond",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 2,
            "can_contain": ["dataJob"],
            "can_be_contained_by": ["system"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "pipeline": {
        "name": "Pipeline",
        "plural_name": "Pipelines",
        "description": "A data pipeline executing ETL or ELT transformations.",
        "granularity": "schema",
        "visual": {
            "icon": "Workflow",
            "color": "#ec4899",
            "color_secondary": "#db2777",
            "shape": "diamond",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 2,
            "can_contain": ["dataJob"],
            "can_be_contained_by": ["system", "domain"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "dataset": {
        "name": "Dataset",
        "plural_name": "Datasets",
        "description": "A tabular dataset, table, or view.",
        "granularity": "table",
        "visual": {
            "icon": "Table2",
            "color": "#22c55e",
            "color_secondary": "#16a34a",
            "shape": "rectangle",
            "size": "sm",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 3,
            "can_contain": ["schemaField", "column"],
            "can_be_contained_by": ["schema", "container", "system", "dataPlatform"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "inline",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
            {"id": "description", "name": "Description", "type": "markdown", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": False, "display_order": 2},
            {"id": "qualified_name", "name": "Qualified Name", "type": "string", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": True, "display_order": 3},
        ],
    },
    "dataJob": {
        "name": "Data Job",
        "plural_name": "Data Jobs",
        "description": "A discrete data transformation or processing job.",
        "granularity": "table",
        "visual": {
            "icon": "Workflow",
            "color": "#ec4899",
            "color_secondary": "#db2777",
            "shape": "diamond",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 3,
            "can_contain": [],
            "can_be_contained_by": ["dataFlow", "pipeline", "schema"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": False,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "dashboard": {
        "name": "Dashboard",
        "plural_name": "Dashboards",
        "description": "A BI dashboard or report grouping charts.",
        "granularity": "table",
        "visual": {
            "icon": "LayoutDashboard",
            "color": "#3b82f6",
            "color_secondary": "#2563eb",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 3,
            "can_contain": ["chart"],
            "can_be_contained_by": ["system", "domain"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": True,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "expand",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "report": {
        "name": "Report",
        "plural_name": "Reports",
        "description": "A report or document produced from data.",
        "granularity": "table",
        "visual": {
            "icon": "FileText",
            "color": "#22c55e",
            "color_secondary": "#16a34a",
            "shape": "rounded",
            "size": "md",
            "border_style": "solid",
            "show_in_minimap": True,
        },
        "hierarchy": {
            "level": 3,
            "can_contain": [],
            "can_be_contained_by": ["system", "domain"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": True,
            "expandable": False,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "schemaField": {
        "name": "Schema Field",
        "plural_name": "Schema Fields",
        "description": "A field or column within a dataset schema.",
        "granularity": "column",
        "visual": {
            "icon": "Columns3",
            "color": "#f59e0b",
            "color_secondary": "#d97706",
            "shape": "rectangle",
            "size": "xs",
            "border_style": "solid",
            "show_in_minimap": False,
        },
        "hierarchy": {
            "level": 4,
            "can_contain": [],
            "can_be_contained_by": ["dataset"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": False,
            "expandable": False,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
            {"id": "data_type", "name": "Data Type", "type": "string", "required": False,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 2},
            {"id": "nullable", "name": "Nullable", "type": "boolean", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": False, "display_order": 3},
        ],
    },
    "column": {
        "name": "Column",
        "plural_name": "Columns",
        "description": "A column in a database table.",
        "granularity": "column",
        "visual": {
            "icon": "Columns3",
            "color": "#f59e0b",
            "color_secondary": "#d97706",
            "shape": "rectangle",
            "size": "xs",
            "border_style": "solid",
            "show_in_minimap": False,
        },
        "hierarchy": {
            "level": 4,
            "can_contain": [],
            "can_be_contained_by": ["dataset"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": False,
            "expandable": False,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
            {"id": "data_type", "name": "Data Type", "type": "string", "required": False,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 2},
        ],
    },
    "chart": {
        "name": "Chart",
        "plural_name": "Charts",
        "description": "A visualization or chart within a dashboard.",
        "granularity": "column",
        "visual": {
            "icon": "BarChart3",
            "color": "#3b82f6",
            "color_secondary": "#2563eb",
            "shape": "rounded",
            "size": "sm",
            "border_style": "solid",
            "show_in_minimap": False,
        },
        "hierarchy": {
            "level": 4,
            "can_contain": [],
            "can_be_contained_by": ["dashboard"],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": False,
            "expandable": False,
            "traceable": True,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
    "glossaryTerm": {
        "name": "Glossary Term",
        "plural_name": "Glossary Terms",
        "description": "A business glossary term or definition.",
        "granularity": "column",
        "visual": {
            "icon": "BookOpen",
            "color": "#a855f7",
            "color_secondary": "#9333ea",
            "shape": "rounded",
            "size": "sm",
            "border_style": "dashed",
            "show_in_minimap": False,
        },
        "hierarchy": {
            "level": 5,
            "can_contain": [],
            "can_be_contained_by": [],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": False,
            "expandable": False,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
            {"id": "definition", "name": "Definition", "type": "markdown", "required": False,
             "show_in_node": False, "show_in_panel": True, "show_in_tooltip": False, "display_order": 2},
        ],
    },
    "tag": {
        "name": "Tag",
        "plural_name": "Tags",
        "description": "A classification tag applied to entities.",
        "granularity": "column",
        "visual": {
            "icon": "Tag",
            "color": "#64748b",
            "color_secondary": "#475569",
            "shape": "rounded",
            "size": "xs",
            "border_style": "solid",
            "show_in_minimap": False,
        },
        "hierarchy": {
            "level": 5,
            "can_contain": [],
            "can_be_contained_by": [],
            "default_expanded": False,
            "roll_up_fields": [],
        },
        "behavior": {
            "selectable": True,
            "draggable": False,
            "expandable": False,
            "traceable": False,
            "click_action": "select",
            "double_click_action": "panel",
            "expansion_mode": "graph",
        },
        "fields": [
            {"id": "name", "name": "Name", "type": "string", "required": True,
             "show_in_node": True, "show_in_panel": True, "show_in_tooltip": True, "display_order": 1},
        ],
    },
}

# ---------------------------------------------------------------------------
# Relationship type defaults
# ---------------------------------------------------------------------------
# Keys are relationship type IDs (uppercase edge label strings from FalkorDB).

SYSTEM_RELATIONSHIP_TYPES: Dict[str, Dict[str, Any]] = {
    "CONTAINS": {
        "name": "Contains",
        "description": "Structural containment: parent physically contains child.",
        "category": "structural",
        "is_containment": True,
        "is_lineage": False,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#6366f1",
            "stroke_width": 2,
            "stroke_style": "solid",
            "animated": False,
            "animation_speed": "normal",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": ["domain", "system", "dataPlatform", "container", "schema", "dataFlow", "pipeline", "dashboard"],
        "target_types": ["system", "dataPlatform", "app", "container", "schema", "dataset", "dataJob", "chart", "report"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "BELONGS_TO": {
        "name": "Belongs To",
        "description": "Inverse containment: child belongs to parent.",
        "category": "structural",
        "is_containment": True,
        "is_lineage": False,
        "direction": "target-to-source",
        "visual": {
            "stroke_color": "#6366f1",
            "stroke_width": 1,
            "stroke_style": "dashed",
            "animated": False,
            "animation_speed": "normal",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": [],
        "target_types": [],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "FLOWS_TO": {
        "name": "Flows To",
        "description": "Data lineage: data flows from source to target.",
        "category": "flow",
        "is_containment": False,
        "is_lineage": True,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#22c55e",
            "stroke_width": 2,
            "stroke_style": "solid",
            "animated": True,
            "animation_speed": "normal",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": ["dataset", "dataJob", "schemaField", "column"],
        "target_types": ["dataset", "dataJob", "schemaField", "column"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "CONSUMES": {
        "name": "Consumes",
        "description": "A job or application reads from a dataset.",
        "category": "flow",
        "is_containment": False,
        "is_lineage": True,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#f59e0b",
            "stroke_width": 2,
            "stroke_style": "solid",
            "animated": True,
            "animation_speed": "slow",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": ["dataJob", "dashboard", "chart"],
        "target_types": ["dataset", "schemaField", "column"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "PRODUCES": {
        "name": "Produces",
        "description": "A job or application writes to a dataset.",
        "category": "flow",
        "is_containment": False,
        "is_lineage": True,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#3b82f6",
            "stroke_width": 2,
            "stroke_style": "solid",
            "animated": True,
            "animation_speed": "slow",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": ["dataJob"],
        "target_types": ["dataset"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "DERIVED_FROM": {
        "name": "Derived From",
        "description": "An entity is semantically derived or computed from another.",
        "category": "flow",
        "is_containment": False,
        "is_lineage": True,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#8b5cf6",
            "stroke_width": 2,
            "stroke_style": "dashed",
            "animated": True,
            "animation_speed": "slow",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": ["dataset", "schemaField", "column"],
        "target_types": ["dataset", "schemaField", "column"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "DEPENDS_ON": {
        "name": "Depends On",
        "description": "A logical dependency between two entities.",
        "category": "association",
        "is_containment": False,
        "is_lineage": True,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#ec4899",
            "stroke_width": 2,
            "stroke_style": "dashed",
            "animated": True,
            "animation_speed": "normal",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": [],
        "target_types": [],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "TAGGED_WITH": {
        "name": "Tagged With",
        "description": "An entity is classified with a tag.",
        "category": "metadata",
        "is_containment": False,
        "is_lineage": False,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#64748b",
            "stroke_width": 1,
            "stroke_style": "dotted",
            "animated": False,
            "animation_speed": "normal",
            "arrow_type": "arrow",
            "curve_type": "straight",
        },
        "source_types": [],
        "target_types": ["tag"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "DEFINED_BY": {
        "name": "Defined By",
        "description": "An entity is defined or governed by a glossary term.",
        "category": "metadata",
        "is_containment": False,
        "is_lineage": False,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#a855f7",
            "stroke_width": 1,
            "stroke_style": "dotted",
            "animated": False,
            "animation_speed": "normal",
            "arrow_type": "arrow",
            "curve_type": "straight",
        },
        "source_types": [],
        "target_types": ["glossaryTerm"],
        "bidirectional": False,
        "show_label": False,
        "label_field": None,
    },
    "AGGREGATED": {
        "name": "Aggregated",
        "description": "A synthetic aggregated lineage edge computed from column-level lineage.",
        "category": "flow",
        "is_containment": False,
        "is_lineage": True,
        "direction": "source-to-target",
        "visual": {
            "stroke_color": "#22c55e",
            "stroke_width": 3,
            "stroke_style": "solid",
            "animated": True,
            "animation_speed": "fast",
            "arrow_type": "arrow",
            "curve_type": "bezier",
        },
        "source_types": [],
        "target_types": [],
        "bidirectional": False,
        "show_label": True,
        "label_field": "source_edge_count",
    },
}

# ---------------------------------------------------------------------------
# System default ontology metadata
# ---------------------------------------------------------------------------
SYSTEM_DEFAULT_ONTOLOGY_NAME = "Synodic Default Ontology"
SYSTEM_DEFAULT_ONTOLOGY_VERSION = 1
